<<<<<<< HEAD
services:
  postgres:
    image: postgres:16
    container_name: b3_postgres
    environment:
      POSTGRES_USER: b3
      POSTGRES_PASSWORD: b3pwd_local_mude
      POSTGRES_DB: b3db
    ports:
      - "5433:5432"
    volumes:
      - b3-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U b3 -d b3db"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  b3-pgdata:
=======
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    ports:
      - "10000:10000"
    volumes:
      - ./azurite_data:/data
>>>>>>> c5b4dfd60e268e8c5bb06c8bdafaf9d1eb16fd14
